# Generated by Django 3.2.9 on 2021-11-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
