# Generated by Django 3.2.9 on 2021-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_turnos_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='doctor',
            field=models.TextField(default='carlos'),
            preserve_default=False,
        ),
    ]
