# Generated by Django 3.2.9 on 2021-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211106_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='turno',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='doctor',
            field=models.TextField(blank=True, default='test'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='is_payed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_lastName',
            field=models.TextField(blank=True, default='DISPONIBLE', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_name',
            field=models.TextField(blank=True, default='TURNO', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
