# Generated by Django 3.2.9 on 2021-11-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211107_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='description',
            field=models.TextField(blank=True, default='--', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_phone',
            field=models.TextField(blank=True, default='--'),
        ),
    ]
