# Generated by Django 3.1 on 2022-12-16 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20211107_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='price',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='description',
            field=models.TextField(blank=True, default='--', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_lastName',
            field=models.TextField(blank=True, default='DISPONIBLE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_name',
            field=models.TextField(blank=True, default='TURNO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_phone',
            field=models.TextField(blank=True, default='---', max_length=30),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=False, null=True)),
                ('payment_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.turno')),
            ],
        ),
    ]
